// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxHZyrke6MTl_L5-EpwAVthOZdN48raGs',
    appId: '1:647934577189:web:39551d37bda44b7aa18dcc',
    messagingSenderId: '647934577189',
    projectId: 'startup-4-8c6a0',
    authDomain: 'startup-4-8c6a0.firebaseapp.com',
    storageBucket: 'startup-4-8c6a0.firebasestorage.app',
    measurementId: 'G-M1KYBXS18J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAagicD20sAq7pMzqSb6FfLtMrOlSfuAwQ',
    appId: '1:647934577189:android:b3d849386f3225b5a18dcc',
    messagingSenderId: '647934577189',
    projectId: 'startup-4-8c6a0',
    storageBucket: 'startup-4-8c6a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbFKMPnjvBZPP_6W9yT9XKAIQ7lFiPqs4',
    appId: '1:647934577189:ios:5f19fbf255b9563aa18dcc',
    messagingSenderId: '647934577189',
    projectId: 'startup-4-8c6a0',
    storageBucket: 'startup-4-8c6a0.firebasestorage.app',
    iosBundleId: 'com.aiman.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbFKMPnjvBZPP_6W9yT9XKAIQ7lFiPqs4',
    appId: '1:647934577189:ios:75f674ae18d28e9fa18dcc',
    messagingSenderId: '647934577189',
    projectId: 'startup-4-8c6a0',
    storageBucket: 'startup-4-8c6a0.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxHZyrke6MTl_L5-EpwAVthOZdN48raGs',
    appId: '1:647934577189:web:bff2254aeb65a6a6a18dcc',
    messagingSenderId: '647934577189',
    projectId: 'startup-4-8c6a0',
    authDomain: 'startup-4-8c6a0.firebaseapp.com',
    storageBucket: 'startup-4-8c6a0.firebasestorage.app',
    measurementId: 'G-H1PSSCNMYM',
  );
}
